# Generated by Django 5.2 on 2025-04-10 18:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('GBP', 'British Pound (£)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)')], max_length=3)),
                ('to_currency', models.CharField(choices=[('GBP', 'British Pound (£)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversion Rate',
                'verbose_name_plural': 'Conversion Rates',
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
    ]
